### ISSUE TITLE
Secrets & API Keys are exposed

### ISSUE THREAD

**Issue by ChristianOrgler** [austrianredcross/stopp-corona-ios#1]
## Description

You can easily get access to your services as they are exposed in unencrypted files. (more information via private messaging as I couldn‘t find a security contact on your website)

## Reproduction steps

Will not disclose here.

Additional helpful information:

• Client ID: 539842520255-k77dikq2s315d6aob********.apps.googleusercontent.com 
• Project ID: stop-corona-14*** 
• API Key: AIzaSyCFhV0VzC************** 
• Google App ID: 1:539842520255:ios:c5****************** 
• API Auth Key: 64165cfc*******************

**Comment by mitsuhiko** [comment]
For responsible disclosure you can use stoppcorona@roteskreuz.at. Unfortunately the button in the issue tracker goes to a German page. This will still be updated.

Generally these credentials are considered public so there shouldn't be a harm with having access to it (they are after all on the device). That said you you believe they can be abused in a way that would cause an issue to the system please reach out.

**Comment by ChristianOrgler** [comment]
I wrote you an email, as they are left out in the code here on github I assumed they are not for the public and can be mis-used to populate wrong data somewhere or obtain information we shouldn't. (Just wanted to raise awareness, feel free to close the issue as it's a security matter :+1:)
