### ISSUE TITLE
iOS shows region change warning

### ISSUE THREAD

**Issue by auerj** [austrianredcross/stopp-corona-ios#100]
## Description

After installing the latest Version (2.0.2) and enabling tracing in the system preferences iOS keeps warning that the region has been changed.
Warning message:

![IMG_2480](https://user-images.githubusercontent.com/6988951/85853137-4bae5780-b7b2-11ea-9da8-eca006dca400.jpg)

System preferences seem fine for me
![Datei_001](https://user-images.githubusercontent.com/6988951/85853225-6e407080-b7b2-11ea-841c-9f530bb1c989.png)

As a user it is unclear if the app is working or not if this message appears.

## Reproduction steps

1. Update to Version 2.0.2
2. Enable tracing in system preferences
3. Message appeard 2 times in the last 4 hours

Additional helpful information:

- Screenshots
- Version of the app

**Comment by bastianh** [comment]
I think this is a know iOS bug, it is also happening with the german corana warn app.
(https://www.iphone-ticker.de/corona-warn-app-fehler-region-fuer-kontaktmitteilungen-geaendert-bekannt-158907/)

**Comment by seehma** [comment]
same here, appears sometimes (about once every two days)...
maybe usefull -> my iPhone is set to English, although iam using it in austria (A1)
just to be sure, is the app working also with this message sometimes appearing?

**Comment by bastianh** [comment]
Yes.. the app is working despite showing this error message
