### ISSUE TITLE
Does not seem to check log

### ISSUE THREAD

**Issue by ghost** [austrianredcross/stopp-corona-ios#101]
I have the app installed since it launched but it seems not to check the the log:

https://imgur.com/a/JLZivIS

Also is it possible to show how many random IDs it collected?

**Comment by schornio** [comment]
No worries, this is about the IDs you get sent when somebody else is tested positive and those IDs get matched against your log of IDs. (https://www.coronawarn.app/de/faq/#no_log_check - also true for this app)

AFAIK there is no way to see how much IDs you have collected.

**Comment by mitsuhiko** [comment]
The link that @schornio posted is correct. There are no uploaded exposure keys yet that your device would have fetched.
