### ISSUE TITLE
App doesn't show if exposure notifcation api doesn't work

### ISSUE THREAD

**Issue by nedt** [austrianredcross/stopp-corona-ios#114]
## Description

In my case I upgraded to the current public beta of iOS 14, which doesn't support the exposure notification API (yet). I expected the app to show an error, but it just says: "Automatischer Handshake: aktiv". Also turned the toggle off and on, but it's still shown as active.
In the iOS settings the message shown is "In deiner Region nicht verfügbar". 
I can't tell if authorization status and status is just returning authorized and active, which would mean it's an apple issue.  It is a beta and might be just broken on the iOS side. But there are other reasons why the framework might fail and there might also be an issue with showing errors in the UI.

## Reproduction steps

1. install app, authorize etc.
2. confirm status is active in the app
3. upgrade to iOS public beta
4. open app and confirm status is still active in app. an error would be expected

Additional helpful information:

- Version of the app: 2.0.5

## What did you expect

An error should be shown, depending on the status enums. Also setting the toggle to active should not be possible.

**Comment by bastianh** [comment]
This is nothing we can fix. The iOS 14 beta does not contain a working exposure framework. If you can turn it on in the app and it shows as active without showing an error, that means the system reports it as active to the app.

**Comment by nedt** [comment]
Just a short note. Reinstalling the app doesn't allow the toggle to be set to active. It also doesn't show any error. But it doesn't seem like iOS is just pretending it's active. Could still be bad error reporting on the framework side.

**Comment by bastianh** [comment]
I'm closing this bug because exposure framework is supported in iOS 14 beta now.
