### ISSUE TITLE
Firebase Config File

### ISSUE THREAD

**Issue by chrisgradl** [austrianredcross/stopp-corona-ios#26]
Can you add the Google-Info.plist File to the project without the Client_ID, API_KEY etc...
It would be interesting to see how the Stopp Corona App  has configured Firebase.
for Example:  IS_ANALYTICS_ENABLED  YES or NO ?

**Comment by bastianh** [comment]
`IS_ANALYTICS_ENABLED` is set to `NO` and we don't include the pod for google analytics in the project ('Firebase/Analytics').
