### ISSUE TITLE
Typo in the string "decission"

### ISSUE THREAD

**Issue by MrHHyde** [austrianredcross/stopp-corona-ios#3]
https://github.com/austrianredcross/stopp-corona-ios/blob/e2ef034aa5fa23718113145f337880f707c52347/CoronaContact/Model/Answer.swift#L20

**Comment by bastianh** [comment]
This typo was unfortunately in the server api ... this is why we have the mapping in place there.

**Comment by mitsuhiko** [comment]
Closing this as wontfix then. Looks like this is the red cross'es "referer" :)
