### ISSUE TITLE
Automatic Handshake does not work

### ISSUE THREAD

**Issue by ghost** [austrianredcross/stopp-corona-ios#43]
## Description

Automatic handshake does not work.

## Reproduction steps

1. enable automatic handshake
2. be around another automatic handshake enabled device for 30 minutes
3. nothing happens

## What did you expect

handshake recoreded

**Comment by falkorichter** [comment]
@hagabla can you tell us what type of phone you are using, which OS version, was bluetooth on? Are you using any bluetooth devices? If so are they connected and working normal?

**Comment by ghost** [comment]
iPhone 11 on latest iOS. BT was on, and is working normally. The other phone in proximity was an iPhone SE

**Comment by uliluckas** [comment]
Were both phones' screens on with the app in foreground?
According to the FAQ (german quote) [1]:
> **Funktioniert der automatische Handschlag auf allen Geräten?** 
> Wenn die App im Hintergrund läuft, kann ein Android Gerät senden und empfangen, ein iOS Gerät jedoch nur senden. 

This says that iOS is not able to receive handshakes when the app is not active (visible on the screen).
Android devices will still capture contacts with you, even when your app is in background. So when you have automatic handshake enabled you will receive warnings from Android users if appropriate.

This is a limitation of iOS and it's BT stack which will be resolved when Stopp Corona integrates the new Google/Apple exposure tracing framework, which is on our short term road map.

1) https://participate.roteskreuz.at/faq_stopp_corona_app/

**Comment by ghost** [comment]
Obviously not in the foreground, since that would make the app totally pointless, who even does that in the real world?
Why include the automatic handshake in the *ios* app if it does not work on *ios*? The "How does it work?" information explaining the automatic handshake even speaks of background activity.

**Comment by bastianh** [comment]
As Uli already explained it is a limitation of iOS that devices can't be found with the current automatic handshake, when the app is not active. When the automatic handshake is enabled other iOS devices (in the foreground) and android devices still can you as a contact on their side.

We are currently in the process of including the iOS exposure framework that was released with iOS 13.5, which will also work in the background.

**Comment by ghost** [comment]
Forget foreground, no one is doing that, ever, designing around that is misguided at best.

2 things can happen:
A) ppl don't know about iOS's limitations and think they are "safe", relying on a feature that is not working
B) ppl  notice and discard the app because its not working

Both options suck, for everyone.

What on earth could possible move you to include this feature in the ios app knowing it does not work as advertised during the worst crises the world has seen since the war.

This is not a game.

**Comment by uliluckas** [comment]
@hagabla certainly we are not expecting you to keep the app in foreground. But we do expect Android devices to be around you every once in a while. If we removed automatic handshake from the iOS version of the App iOS users would miss out on infection warnings from Android users around them.

And yes, we are aware that the perfect solution would also fully work between ios/ios. But we have to work with the features the OSes provide. That is the reason we will be switching to the Google/Apple framework.

**Comment by ghost** [comment]
I understand your dilemma but the thing is, your app seems broken now. That is the impression one gets on ios and as you are well aware you only get one chance to make a first impression.

This could/should be explained somewhere, preferable under the How it works (i) thingie directly under the automatic Handshake. "Not all devices and operating systems are supported" is pointless as well, it's a message that conveys 0 useful information for ppl to act on. Are we supposed to guess if our device is supported? Or the OS? Are we supposed to all open an issue on github. Do you think people will research that? Whats the point? You see the issue here right? 

It's kinda like Schrödingers Handshake.

Out of curiosity, whats the timeline for the exposure Api to get implemented?

**Comment by bastianh** [comment]
this article is also about the problem with iOS devices https://www.krone.at/2158450 and it mentions that the timeline for implementing the feature is the first half on june.
I'll close this bug report for now.
