### ISSUE TITLE
Not able to rebuild the app for iOs

### ISSUE THREAD

**Issue by pelinquin** [austrianredcross/stopp-corona-ios#6]
Hello,

I have got one last error while trying to build the app for iOs on Xcode
I followed the readme file, done the pod install and setup all Google keys (why needed for iOs !)!

Here the error message:
Multiple commands produce '/Users/adox/Library/Developer/Xcode/DerivedData/CoronaContact-ermaebrhzdaqmqcbqqzfxelchnoj/Build/Products/Development-iphoneos/Stopp Corona.app/Assets.car':
1) Target 'CoronaContact' (project 'CoronaContact') has compile command with input '/Users/adox/Downloads/stopp-corona-ios-master/CoronaContact/Resources/Assets.xcassets'
2) That command depends on command in Target 'CoronaContact' (project 'CoronaContact'): script phase “[CP] Copy Pods Resources”

If you want this project to be really OpenSource, you should make it easily configurable for any developper in the world.

Please give us exemple of configuration.

Best regards

**Comment by bastianh** [comment]
The google keys/files are needed for firebase messaging and the google nearby library.

To fix your build problem please make sure that the legacy build system is enabled for this project. It should be enabled in the included project files, but sometimes xcode suggests to disable it, so maybe that happened.

If you need more assistance, feel free to ask.
